[package]
name = "eddsa"
type = "lib"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
noir_edwards = { tag = "v0.2.1", git = "https://github.com/noir-lang/noir-edwards" }
poseidon = { tag = "v0.2.6", git = "https://github.com/noir-lang/poseidon" }
